version: "3.8"

services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "2000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@database/manager
    links:
      - database

  database:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manager
