version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "80:80"
    env_file: .flaskenv
    environment:
      PORT: 80
      DATABASE_URL: postgresql://postgres:postgres@database/manager
    links:
      - database

  database:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manager
