name: CI
on:
  push:
  workflow_dispatch:

jobs:

  runner-job:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Init
      run: |
        make init

    - name: Lint
      run: |
        make lint

    - name: Setup database
      run: |
        psql -h localhost -c "CREATE DATABASE data_manager WITH TEMPLATE postgres" -U postgres
      env:
        PGPASSWORD: postgres

    - name: Migration database
      run: |
        make upgrade-db
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost/data_manager

    - name: Test
      run: |
        make load-test-data
        make test
        make test-functional
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost/data_manager
